/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YttaRouteImport } from './routes/ytta'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YttaIndexRouteImport } from './routes/ytta/index'
import { Route as GameSlugRouteImport } from './routes/game.$slug'
import { Route as YttaGameIndexRouteImport } from './routes/ytta/game/index'
import { Route as YttaGameCreateRouteImport } from './routes/ytta/game/create'
import { Route as YttaGameSlugEditRouteImport } from './routes/ytta/game/$slug/edit'
import { Route as YttaGameSlugItemIndexRouteImport } from './routes/ytta/game/$slug/item/index'
import { Route as YttaGameSlugItemCreateRouteImport } from './routes/ytta/game/$slug/item/create'
import { Route as YttaGameSlugItemItemSlugRouteImport } from './routes/ytta/game/$slug/item/$itemSlug'

const YttaRoute = YttaRouteImport.update({
  id: '/ytta',
  path: '/ytta',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YttaIndexRoute = YttaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YttaRoute,
} as any)
const GameSlugRoute = GameSlugRouteImport.update({
  id: '/game/$slug',
  path: '/game/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const YttaGameIndexRoute = YttaGameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => YttaRoute,
} as any)
const YttaGameCreateRoute = YttaGameCreateRouteImport.update({
  id: '/game/create',
  path: '/game/create',
  getParentRoute: () => YttaRoute,
} as any)
const YttaGameSlugEditRoute = YttaGameSlugEditRouteImport.update({
  id: '/game/$slug/edit',
  path: '/game/$slug/edit',
  getParentRoute: () => YttaRoute,
} as any)
const YttaGameSlugItemIndexRoute = YttaGameSlugItemIndexRouteImport.update({
  id: '/game/$slug/item/',
  path: '/game/$slug/item/',
  getParentRoute: () => YttaRoute,
} as any)
const YttaGameSlugItemCreateRoute = YttaGameSlugItemCreateRouteImport.update({
  id: '/game/$slug/item/create',
  path: '/game/$slug/item/create',
  getParentRoute: () => YttaRoute,
} as any)
const YttaGameSlugItemItemSlugRoute =
  YttaGameSlugItemItemSlugRouteImport.update({
    id: '/game/$slug/item/$itemSlug',
    path: '/game/$slug/item/$itemSlug',
    getParentRoute: () => YttaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/ytta': typeof YttaRouteWithChildren
  '/game/$slug': typeof GameSlugRoute
  '/ytta/': typeof YttaIndexRoute
  '/ytta/game/create': typeof YttaGameCreateRoute
  '/ytta/game': typeof YttaGameIndexRoute
  '/ytta/game/$slug/edit': typeof YttaGameSlugEditRoute
  '/ytta/game/$slug/item/$itemSlug': typeof YttaGameSlugItemItemSlugRoute
  '/ytta/game/$slug/item/create': typeof YttaGameSlugItemCreateRoute
  '/ytta/game/$slug/item': typeof YttaGameSlugItemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/game/$slug': typeof GameSlugRoute
  '/ytta': typeof YttaIndexRoute
  '/ytta/game/create': typeof YttaGameCreateRoute
  '/ytta/game': typeof YttaGameIndexRoute
  '/ytta/game/$slug/edit': typeof YttaGameSlugEditRoute
  '/ytta/game/$slug/item/$itemSlug': typeof YttaGameSlugItemItemSlugRoute
  '/ytta/game/$slug/item/create': typeof YttaGameSlugItemCreateRoute
  '/ytta/game/$slug/item': typeof YttaGameSlugItemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/ytta': typeof YttaRouteWithChildren
  '/game/$slug': typeof GameSlugRoute
  '/ytta/': typeof YttaIndexRoute
  '/ytta/game/create': typeof YttaGameCreateRoute
  '/ytta/game/': typeof YttaGameIndexRoute
  '/ytta/game/$slug/edit': typeof YttaGameSlugEditRoute
  '/ytta/game/$slug/item/$itemSlug': typeof YttaGameSlugItemItemSlugRoute
  '/ytta/game/$slug/item/create': typeof YttaGameSlugItemCreateRoute
  '/ytta/game/$slug/item/': typeof YttaGameSlugItemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/todos'
    | '/ytta'
    | '/game/$slug'
    | '/ytta/'
    | '/ytta/game/create'
    | '/ytta/game'
    | '/ytta/game/$slug/edit'
    | '/ytta/game/$slug/item/$itemSlug'
    | '/ytta/game/$slug/item/create'
    | '/ytta/game/$slug/item'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/todos'
    | '/game/$slug'
    | '/ytta'
    | '/ytta/game/create'
    | '/ytta/game'
    | '/ytta/game/$slug/edit'
    | '/ytta/game/$slug/item/$itemSlug'
    | '/ytta/game/$slug/item/create'
    | '/ytta/game/$slug/item'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/todos'
    | '/ytta'
    | '/game/$slug'
    | '/ytta/'
    | '/ytta/game/create'
    | '/ytta/game/'
    | '/ytta/game/$slug/edit'
    | '/ytta/game/$slug/item/$itemSlug'
    | '/ytta/game/$slug/item/create'
    | '/ytta/game/$slug/item/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TodosRoute: typeof TodosRoute
  YttaRoute: typeof YttaRouteWithChildren
  GameSlugRoute: typeof GameSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ytta': {
      id: '/ytta'
      path: '/ytta'
      fullPath: '/ytta'
      preLoaderRoute: typeof YttaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ytta/': {
      id: '/ytta/'
      path: '/'
      fullPath: '/ytta/'
      preLoaderRoute: typeof YttaIndexRouteImport
      parentRoute: typeof YttaRoute
    }
    '/game/$slug': {
      id: '/game/$slug'
      path: '/game/$slug'
      fullPath: '/game/$slug'
      preLoaderRoute: typeof GameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ytta/game/': {
      id: '/ytta/game/'
      path: '/game'
      fullPath: '/ytta/game'
      preLoaderRoute: typeof YttaGameIndexRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/game/create': {
      id: '/ytta/game/create'
      path: '/game/create'
      fullPath: '/ytta/game/create'
      preLoaderRoute: typeof YttaGameCreateRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/game/$slug/edit': {
      id: '/ytta/game/$slug/edit'
      path: '/game/$slug/edit'
      fullPath: '/ytta/game/$slug/edit'
      preLoaderRoute: typeof YttaGameSlugEditRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/game/$slug/item/': {
      id: '/ytta/game/$slug/item/'
      path: '/game/$slug/item'
      fullPath: '/ytta/game/$slug/item'
      preLoaderRoute: typeof YttaGameSlugItemIndexRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/game/$slug/item/create': {
      id: '/ytta/game/$slug/item/create'
      path: '/game/$slug/item/create'
      fullPath: '/ytta/game/$slug/item/create'
      preLoaderRoute: typeof YttaGameSlugItemCreateRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/game/$slug/item/$itemSlug': {
      id: '/ytta/game/$slug/item/$itemSlug'
      path: '/game/$slug/item/$itemSlug'
      fullPath: '/ytta/game/$slug/item/$itemSlug'
      preLoaderRoute: typeof YttaGameSlugItemItemSlugRouteImport
      parentRoute: typeof YttaRoute
    }
  }
}

interface YttaRouteChildren {
  YttaIndexRoute: typeof YttaIndexRoute
  YttaGameCreateRoute: typeof YttaGameCreateRoute
  YttaGameIndexRoute: typeof YttaGameIndexRoute
  YttaGameSlugEditRoute: typeof YttaGameSlugEditRoute
  YttaGameSlugItemItemSlugRoute: typeof YttaGameSlugItemItemSlugRoute
  YttaGameSlugItemCreateRoute: typeof YttaGameSlugItemCreateRoute
  YttaGameSlugItemIndexRoute: typeof YttaGameSlugItemIndexRoute
}

const YttaRouteChildren: YttaRouteChildren = {
  YttaIndexRoute: YttaIndexRoute,
  YttaGameCreateRoute: YttaGameCreateRoute,
  YttaGameIndexRoute: YttaGameIndexRoute,
  YttaGameSlugEditRoute: YttaGameSlugEditRoute,
  YttaGameSlugItemItemSlugRoute: YttaGameSlugItemItemSlugRoute,
  YttaGameSlugItemCreateRoute: YttaGameSlugItemCreateRoute,
  YttaGameSlugItemIndexRoute: YttaGameSlugItemIndexRoute,
}

const YttaRouteWithChildren = YttaRoute._addFileChildren(YttaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TodosRoute: TodosRoute,
  YttaRoute: YttaRouteWithChildren,
  GameSlugRoute: GameSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
