/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YttaRouteImport } from './routes/ytta'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FindOrderRouteImport } from './routes/find-order'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YttaIndexRouteImport } from './routes/ytta/index'
import { Route as YttaReportsRouteImport } from './routes/ytta/reports'
import { Route as YttaMediaRouteImport } from './routes/ytta/media'
import { Route as YttaContactRouteImport } from './routes/ytta/contact'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as GameSlugRouteImport } from './routes/game.$slug'
import { Route as YttaGameIndexRouteImport } from './routes/ytta/game/index'
import { Route as YttaGameCreateRouteImport } from './routes/ytta/game/create'
import { Route as YttaGameSlugEditRouteImport } from './routes/ytta/game/$slug/edit'
import { Route as YttaGameSlugItemIndexRouteImport } from './routes/ytta/game/$slug/item/index'
import { Route as YttaGameSlugItemCreateRouteImport } from './routes/ytta/game/$slug/item/create'
import { Route as YttaGameSlugItemItemSlugRouteImport } from './routes/ytta/game/$slug/item/$itemSlug'

const YttaRoute = YttaRouteImport.update({
  id: '/ytta',
  path: '/ytta',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FindOrderRoute = FindOrderRouteImport.update({
  id: '/find-order',
  path: '/find-order',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YttaIndexRoute = YttaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YttaRoute,
} as any)
const YttaReportsRoute = YttaReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => YttaRoute,
} as any)
const YttaMediaRoute = YttaMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => YttaRoute,
} as any)
const YttaContactRoute = YttaContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => YttaRoute,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSlugRoute = GameSlugRouteImport.update({
  id: '/game/$slug',
  path: '/game/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const YttaGameIndexRoute = YttaGameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => YttaRoute,
} as any)
const YttaGameCreateRoute = YttaGameCreateRouteImport.update({
  id: '/game/create',
  path: '/game/create',
  getParentRoute: () => YttaRoute,
} as any)
const YttaGameSlugEditRoute = YttaGameSlugEditRouteImport.update({
  id: '/game/$slug/edit',
  path: '/game/$slug/edit',
  getParentRoute: () => YttaRoute,
} as any)
const YttaGameSlugItemIndexRoute = YttaGameSlugItemIndexRouteImport.update({
  id: '/game/$slug/item/',
  path: '/game/$slug/item/',
  getParentRoute: () => YttaRoute,
} as any)
const YttaGameSlugItemCreateRoute = YttaGameSlugItemCreateRouteImport.update({
  id: '/game/$slug/item/create',
  path: '/game/$slug/item/create',
  getParentRoute: () => YttaRoute,
} as any)
const YttaGameSlugItemItemSlugRoute =
  YttaGameSlugItemItemSlugRouteImport.update({
    id: '/game/$slug/item/$itemSlug',
    path: '/game/$slug/item/$itemSlug',
    getParentRoute: () => YttaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/find-order': typeof FindOrderRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/ytta': typeof YttaRouteWithChildren
  '/game/$slug': typeof GameSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/ytta/contact': typeof YttaContactRoute
  '/ytta/media': typeof YttaMediaRoute
  '/ytta/reports': typeof YttaReportsRoute
  '/ytta/': typeof YttaIndexRoute
  '/ytta/game/create': typeof YttaGameCreateRoute
  '/ytta/game': typeof YttaGameIndexRoute
  '/ytta/game/$slug/edit': typeof YttaGameSlugEditRoute
  '/ytta/game/$slug/item/$itemSlug': typeof YttaGameSlugItemItemSlugRoute
  '/ytta/game/$slug/item/create': typeof YttaGameSlugItemCreateRoute
  '/ytta/game/$slug/item': typeof YttaGameSlugItemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/find-order': typeof FindOrderRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/game/$slug': typeof GameSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/ytta/contact': typeof YttaContactRoute
  '/ytta/media': typeof YttaMediaRoute
  '/ytta/reports': typeof YttaReportsRoute
  '/ytta': typeof YttaIndexRoute
  '/ytta/game/create': typeof YttaGameCreateRoute
  '/ytta/game': typeof YttaGameIndexRoute
  '/ytta/game/$slug/edit': typeof YttaGameSlugEditRoute
  '/ytta/game/$slug/item/$itemSlug': typeof YttaGameSlugItemItemSlugRoute
  '/ytta/game/$slug/item/create': typeof YttaGameSlugItemCreateRoute
  '/ytta/game/$slug/item': typeof YttaGameSlugItemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/find-order': typeof FindOrderRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/ytta': typeof YttaRouteWithChildren
  '/game/$slug': typeof GameSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/ytta/contact': typeof YttaContactRoute
  '/ytta/media': typeof YttaMediaRoute
  '/ytta/reports': typeof YttaReportsRoute
  '/ytta/': typeof YttaIndexRoute
  '/ytta/game/create': typeof YttaGameCreateRoute
  '/ytta/game/': typeof YttaGameIndexRoute
  '/ytta/game/$slug/edit': typeof YttaGameSlugEditRoute
  '/ytta/game/$slug/item/$itemSlug': typeof YttaGameSlugItemItemSlugRoute
  '/ytta/game/$slug/item/create': typeof YttaGameSlugItemCreateRoute
  '/ytta/game/$slug/item/': typeof YttaGameSlugItemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/find-order'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/terms'
    | '/ytta'
    | '/game/$slug'
    | '/order/$orderId'
    | '/ytta/contact'
    | '/ytta/media'
    | '/ytta/reports'
    | '/ytta/'
    | '/ytta/game/create'
    | '/ytta/game'
    | '/ytta/game/$slug/edit'
    | '/ytta/game/$slug/item/$itemSlug'
    | '/ytta/game/$slug/item/create'
    | '/ytta/game/$slug/item'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/find-order'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/terms'
    | '/game/$slug'
    | '/order/$orderId'
    | '/ytta/contact'
    | '/ytta/media'
    | '/ytta/reports'
    | '/ytta'
    | '/ytta/game/create'
    | '/ytta/game'
    | '/ytta/game/$slug/edit'
    | '/ytta/game/$slug/item/$itemSlug'
    | '/ytta/game/$slug/item/create'
    | '/ytta/game/$slug/item'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/find-order'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/terms'
    | '/ytta'
    | '/game/$slug'
    | '/order/$orderId'
    | '/ytta/contact'
    | '/ytta/media'
    | '/ytta/reports'
    | '/ytta/'
    | '/ytta/game/create'
    | '/ytta/game/'
    | '/ytta/game/$slug/edit'
    | '/ytta/game/$slug/item/$itemSlug'
    | '/ytta/game/$slug/item/create'
    | '/ytta/game/$slug/item/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  FaqRoute: typeof FaqRoute
  FindOrderRoute: typeof FindOrderRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  YttaRoute: typeof YttaRouteWithChildren
  GameSlugRoute: typeof GameSlugRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ytta': {
      id: '/ytta'
      path: '/ytta'
      fullPath: '/ytta'
      preLoaderRoute: typeof YttaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-order': {
      id: '/find-order'
      path: '/find-order'
      fullPath: '/find-order'
      preLoaderRoute: typeof FindOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ytta/': {
      id: '/ytta/'
      path: '/'
      fullPath: '/ytta/'
      preLoaderRoute: typeof YttaIndexRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/reports': {
      id: '/ytta/reports'
      path: '/reports'
      fullPath: '/ytta/reports'
      preLoaderRoute: typeof YttaReportsRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/media': {
      id: '/ytta/media'
      path: '/media'
      fullPath: '/ytta/media'
      preLoaderRoute: typeof YttaMediaRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/contact': {
      id: '/ytta/contact'
      path: '/contact'
      fullPath: '/ytta/contact'
      preLoaderRoute: typeof YttaContactRouteImport
      parentRoute: typeof YttaRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$slug': {
      id: '/game/$slug'
      path: '/game/$slug'
      fullPath: '/game/$slug'
      preLoaderRoute: typeof GameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ytta/game/': {
      id: '/ytta/game/'
      path: '/game'
      fullPath: '/ytta/game'
      preLoaderRoute: typeof YttaGameIndexRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/game/create': {
      id: '/ytta/game/create'
      path: '/game/create'
      fullPath: '/ytta/game/create'
      preLoaderRoute: typeof YttaGameCreateRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/game/$slug/edit': {
      id: '/ytta/game/$slug/edit'
      path: '/game/$slug/edit'
      fullPath: '/ytta/game/$slug/edit'
      preLoaderRoute: typeof YttaGameSlugEditRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/game/$slug/item/': {
      id: '/ytta/game/$slug/item/'
      path: '/game/$slug/item'
      fullPath: '/ytta/game/$slug/item'
      preLoaderRoute: typeof YttaGameSlugItemIndexRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/game/$slug/item/create': {
      id: '/ytta/game/$slug/item/create'
      path: '/game/$slug/item/create'
      fullPath: '/ytta/game/$slug/item/create'
      preLoaderRoute: typeof YttaGameSlugItemCreateRouteImport
      parentRoute: typeof YttaRoute
    }
    '/ytta/game/$slug/item/$itemSlug': {
      id: '/ytta/game/$slug/item/$itemSlug'
      path: '/game/$slug/item/$itemSlug'
      fullPath: '/ytta/game/$slug/item/$itemSlug'
      preLoaderRoute: typeof YttaGameSlugItemItemSlugRouteImport
      parentRoute: typeof YttaRoute
    }
  }
}

interface YttaRouteChildren {
  YttaContactRoute: typeof YttaContactRoute
  YttaMediaRoute: typeof YttaMediaRoute
  YttaReportsRoute: typeof YttaReportsRoute
  YttaIndexRoute: typeof YttaIndexRoute
  YttaGameCreateRoute: typeof YttaGameCreateRoute
  YttaGameIndexRoute: typeof YttaGameIndexRoute
  YttaGameSlugEditRoute: typeof YttaGameSlugEditRoute
  YttaGameSlugItemItemSlugRoute: typeof YttaGameSlugItemItemSlugRoute
  YttaGameSlugItemCreateRoute: typeof YttaGameSlugItemCreateRoute
  YttaGameSlugItemIndexRoute: typeof YttaGameSlugItemIndexRoute
}

const YttaRouteChildren: YttaRouteChildren = {
  YttaContactRoute: YttaContactRoute,
  YttaMediaRoute: YttaMediaRoute,
  YttaReportsRoute: YttaReportsRoute,
  YttaIndexRoute: YttaIndexRoute,
  YttaGameCreateRoute: YttaGameCreateRoute,
  YttaGameIndexRoute: YttaGameIndexRoute,
  YttaGameSlugEditRoute: YttaGameSlugEditRoute,
  YttaGameSlugItemItemSlugRoute: YttaGameSlugItemItemSlugRoute,
  YttaGameSlugItemCreateRoute: YttaGameSlugItemCreateRoute,
  YttaGameSlugItemIndexRoute: YttaGameSlugItemIndexRoute,
}

const YttaRouteWithChildren = YttaRoute._addFileChildren(YttaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  FaqRoute: FaqRoute,
  FindOrderRoute: FindOrderRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  YttaRoute: YttaRouteWithChildren,
  GameSlugRoute: GameSlugRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
